lucky_numbers = [4, 8, 15, 16, 23,42]
friends = ["Jim", "Kevin", "Chinlu"]
friends.sort()
print(friends)
friends.extend(lucky_numbers)
friends.append("Creed")
print(friends)
print(friends[0])
print(friends[-1])
print(friends[0 : 2])
friends.insert(1, "Kelly")
print(friends)
friends.remove("Jim")
print(friends)
print(friends.index("Kelly"))
friends2 = friends.copy()
print(friends2)
